services:
  web:
    build: .
    container_name: flask_whiteboard
    command: gunicorn -k eventlet -w 1 -b 0.0.0.0:5000 run:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: whiteboard_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whiteboard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: whiteboard_redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A make_celery.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A make_celery.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
